# Generated by Django 5.2.4 on 2026-05-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ota", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceotastatus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="firmware",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("shelly_em", "Shelly EM"),
                    ("nous_at", "Nous AT"),
                    ("zigbee_sensor", "Zigbee Sensor"),
                    ("auto_detected", "Auto Detected"),
                    ("sun2000", "Huawei SUN2000"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="firmware",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rolloutplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
