# Generated by Django 5.2.5 on 2025-08-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("shelly_em", "Shelly EM"),
                    ("nous_at", "Nous AT"),
                    ("zigbee_sensor", "Zigbee Sensor"),
                    ("auto_detected", "Auto Detected"),
                ],
                max_length=20,
            ),
        ),
    ]
