# Generated by Django 5.1.5 on 2025-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_device_device_type"),  # 👈 ajustează după ultima ta migrare existentă
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("shelly_em", "Shelly EM"),
                    ("nous_at", "Nous AT"),
                    ("zigbee_sensor", "Zigbee Sensor"),
                    ("auto_detected", "Auto Detected"),
                ],
                max_length=20,
            ),
        ),
    ]
