# Generated by Django 5.2.4 on 2026-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0010_alter_device_device_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="capabilities",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
