# Generated by Django 5.2.4 on 2026-05-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationchannel",
            name="config",
            field=models.JSONField(
                help_text="Type-specific config. See model docstring."
            ),
        ),
    ]
