# Generated by Django 5.2.4 on 2026-05-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="actions",
            field=models.JSONField(
                help_text="List of actions: downlink, notify, webhook, set_shadow."
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="conditions",
            field=models.JSONField(
                help_text="Condition DSL tree. See API docs for schema."
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="cooldown_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Min seconds between consecutive firings for same device.",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="trigger_stream_pattern",
            field=models.CharField(
                default="*",
                help_text='Stream name(s): "*", "telemetry", "telemetry,emeter"',
                max_length=200,
            ),
        ),
    ]
